export const INCREMENT_LOGO_SPEED = 'INCREMENT_LOGO_SPEED'
export type INCREMENT_LOGO_SPEED = typeof INCREMENT_LOGO_SPEED

export const DECREMENT_LOGO_SPEED = 'DECREMENT_LOGO_SPEED'
export type DECREMENT_LOGO_SPEED = typeof DECREMENT_LOGO_SPEED
